FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.prod.conf /etc/nginx/conf.d

# COPY ./init-letsencrypt.sh .
# RUN sed -i 's/\r$//g'  $APP_HOME/init-letsencrypt.sh
# RUN chmod +x  $APP_HOME/init-letsencrypt.sh

# ENTRYPOINT ["/init-letsencrypt.sh"]